package RegistrationManagementSystem;
// Generated Apr 8, 2022 1:19:14 AM by Hibernate Tools 4.3.1



/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String CId;
     private Person person;
     private String CName;

    public Course() {
    }

	
    public Course(String CId) {
        this.CId = CId;
    }
    public Course(String CId, Person person, String CName) {
       this.CId = CId;
       this.person = person;
       this.CName = CName;
    }
   
    public String getCId() {
        return this.CId;
    }
    
    public void setCId(String CId) {
        this.CId = CId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getCName() {
        return this.CName;
    }
    
    public void setCName(String CName) {
        this.CName = CName;
    }




}


