package RegistrationManagementSystem;
// Generated Apr 8, 2022 1:19:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private String PId;
     private String PName;
     private String PType;
     private String courseId;
     private Set courses = new HashSet(0);

    public Person() {
    }

	
    public Person(String PId) {
        this.PId = PId;
    }
    public Person(String PId, String PName, String PType, String courseId, Set courses) {
       this.PId = PId;
       this.PName = PName;
       this.PType = PType;
       this.courseId = courseId;
       this.courses = courses;
    }
   
    public String getPId() {
        return this.PId;
    }
    
    public void setPId(String PId) {
        this.PId = PId;
    }
    public String getPName() {
        return this.PName;
    }
    
    public void setPName(String PName) {
        this.PName = PName;
    }
    public String getPType() {
        return this.PType;
    }
    
    public void setPType(String PType) {
        this.PType = PType;
    }
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
}


