/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistrationManagementSystem;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.*; 
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Willy
 */
public class RegistrationApp extends javax.swing.JFrame {
    DefaultListModel studentModel = new DefaultListModel();
    /**
     * Creates new form RegistrationApp
     */
    public RegistrationApp() {
        initComponents();
        addItemInLecturerCombo();
        addItemInStudentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        StudentPanel = new javax.swing.JPanel();
        SubStudPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StudID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        StudName = new javax.swing.JTextField();
        StudSaveButton = new javax.swing.JButton();
        LecturerPanel = new javax.swing.JPanel();
        SubLecPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LecID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LecName = new javax.swing.JTextField();
        LecSaveButton = new javax.swing.JButton();
        CoursePanel = new javax.swing.JPanel();
        SubCrsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        RefreshButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CrsID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CrsName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CrsInstructor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        CrsSaveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubStudPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Registration");

        jLabel2.setText("Student ID");

        StudID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setText("Student Name");

        StudName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        StudSaveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        StudSaveButton.setText("SAVE");
        StudSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubStudPanelLayout = new javax.swing.GroupLayout(SubStudPanel);
        SubStudPanel.setLayout(SubStudPanelLayout);
        SubStudPanelLayout.setHorizontalGroup(
            SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubStudPanelLayout.createSequentialGroup()
                .addGroup(SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SubStudPanelLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubStudPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StudName)))
                    .addGroup(SubStudPanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(StudSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        SubStudPanelLayout.setVerticalGroup(
            SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubStudPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(SubStudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(StudSaveButton)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubStudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SubStudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", StudentPanel);

        SubLecPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Lecturer Registration");

        jLabel5.setText("Lecturer ID");

        jLabel6.setText("Lecturer Name");

        LecSaveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LecSaveButton.setText("SAVE");
        LecSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SubLecPanelLayout = new javax.swing.GroupLayout(SubLecPanel);
        SubLecPanel.setLayout(SubLecPanelLayout);
        SubLecPanelLayout.setHorizontalGroup(
            SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubLecPanelLayout.createSequentialGroup()
                .addGroup(SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubLecPanelLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubLecPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LecID, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(LecName)))
                    .addGroup(SubLecPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(LecSaveButton)))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        SubLecPanelLayout.setVerticalGroup(
            SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubLecPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LecID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(SubLecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LecName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(LecSaveButton)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LecturerPanelLayout = new javax.swing.GroupLayout(LecturerPanel);
        LecturerPanel.setLayout(LecturerPanelLayout);
        LecturerPanelLayout.setHorizontalGroup(
            LecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubLecPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LecturerPanelLayout.setVerticalGroup(
            LecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SubLecPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lecturer", LecturerPanel);

        SubCrsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Course Registration");

        RefreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(153, 153, 255));
        RefreshButton.setText("Refresh");

        jLabel8.setText("Course ID");

        jLabel9.setText("Course Name");

        CrsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrsNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Instructor");

        jLabel11.setText("Student List");

        CrsSaveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CrsSaveButton.setText("SAVE");
        CrsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrsSaveButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(StudList);

        javax.swing.GroupLayout SubCrsPanelLayout = new javax.swing.GroupLayout(SubCrsPanel);
        SubCrsPanel.setLayout(SubCrsPanelLayout);
        SubCrsPanelLayout.setHorizontalGroup(
            SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubCrsPanelLayout.createSequentialGroup()
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SubCrsPanelLayout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(RefreshButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SubCrsPanelLayout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CrsInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CrsName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CrsID, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SubCrsPanelLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(CrsSaveButton)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        SubCrsPanelLayout.setVerticalGroup(
            SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubCrsPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshButton))
                .addGap(32, 32, 32)
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrsInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SubCrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubCrsPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SubCrsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(CrsSaveButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CoursePanelLayout = new javax.swing.GroupLayout(CoursePanel);
        CoursePanel.setLayout(CoursePanelLayout);
        CoursePanelLayout.setHorizontalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addComponent(SubCrsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CoursePanelLayout.setVerticalGroup(
            CoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursePanelLayout.createSequentialGroup()
                .addComponent(SubCrsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Course", CoursePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LecSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecSaveButtonActionPerformed
         if(LecID.getText().equals("") || LecName.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please Fill Empty fields ","Empty Field",JOptionPane.ERROR_MESSAGE);
      }else{
        if(LecID.getText().length()==5){
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.beginTransaction();
        try{
           Person lec = new Person();
           lec.setPId(LecID.getText());
           lec.setPName(LecName.getText());
           lec.setPType("Lecturer");
           session.save(lec);
           tx.commit();
           JOptionPane.showMessageDialog(this,"Successful Registered","DATA SAVED",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(HibernateException ex){
            System.out.println(ex);
        }finally{
        session.close();
        }
        }else{
        JOptionPane.showMessageDialog(this,"You need a maximum of 5 Digits","Incorrect Lecturer ID",JOptionPane.ERROR_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_LecSaveButtonActionPerformed

    private void CrsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrsNameActionPerformed

    private void StudSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudSaveButtonActionPerformed
        if(StudID.getText().equals("") || StudName.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please Fill Empty fields ","Empty Field",JOptionPane.ERROR_MESSAGE);
      }else{
        if(StudID.getText().length()==5){
            //calling database and save data
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.beginTransaction();
        try{
           Person student = new Person();
           student.setPId(StudID.getText());
           student.setPName(StudName.getText());
           student.setPType("Student");
           session.save(student);
           tx.commit();
           JOptionPane.showMessageDialog(this,"Successful Registered","DATA SAVED",JOptionPane.INFORMATION_MESSAGE);
           if(JOptionPane.OK_OPTION ==0){
               StudID.setText("");
               StudName.setText("");
               studentModel.removeAllElements();
               addItemInStudentList();
           }
            
        }catch(HibernateException ex){
            System.out.println(ex);
        }finally{
        session.close();
        }
        }else{
        JOptionPane.showMessageDialog(this,"You need a maximum of 5 Digits","Incorrect Student ID",JOptionPane.ERROR_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_StudSaveButtonActionPerformed

    private void CrsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrsSaveButtonActionPerformed
         if(CrsID.getText().equals("") || CrsName.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Please Fill Empty fields ","Empty Field",JOptionPane.ERROR_MESSAGE);
      }else{
        if(CrsID.getText().length()==5){
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.beginTransaction();
        try{
           Course crs = new Course();
           crs.setCId(CrsID.getText());
           crs.setCName(CrsName.getText());
           String selectedLect = CrsInstructor.getSelectedItem().toString();
           Person lect = new Person();
           lect.setPId(selectedLect.substring(0, 5));
           crs.setPerson(lect);
           session.save(crs);
           //UPDATE TABLE FOR PERSON
           String selectedStudent = StudList.getSelectedValue();
           Person updateStudent =(Person) session.get(Person.class, selectedStudent.substring(0, 5));
           updateStudent.setCourseId(CrsID.getText());
           session.update(updateStudent);
           tx.commit();
           JOptionPane.showMessageDialog(this,"Successful Registered","DATA SAVED",JOptionPane.INFORMATION_MESSAGE);
           if(JOptionPane.OK_OPTION ==0){
               CrsID.setText("");
               CrsName.setText("");
           }
            
        }catch(HibernateException ex){
            System.out.println(ex);
        }finally{
        session.close();
        }
        }else{
        JOptionPane.showMessageDialog(this,"You need a maximum of 5 Digits","Incorrect Course ID",JOptionPane.ERROR_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_CrsSaveButtonActionPerformed

    
    private void addItemInLecturerCombo(){
    Session session = HibernateUtil.getSessionFactory().openSession();
    List lectList = session.createQuery("from Person p where p.PType='Lecturer'").list();
    Iterator iterator = lectList.iterator();
    while (iterator.hasNext()){
        Person lect =(Person)iterator.next();
        CrsInstructor.addItem(lect.getPId()+"-"+lect.getPName());
        
    }
    
    }
     private void addItemInStudentList(){
    Session session = HibernateUtil.getSessionFactory().openSession();
    List lectList = session.createQuery("from Person p where p.PType='Student'").list();
    Iterator iterator = lectList.iterator();
    while (iterator.hasNext()){
        Person stud =(Person)iterator.next();
        studentModel.addElement(stud.getPId()+"-"+stud.getPName());
        
    }
    StudList.setModel(studentModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    } catch (java.lang.InstantiationException ex) {
                        Logger.getLogger(RegistrationApp.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoursePanel;
    private javax.swing.JTextField CrsID;
    private javax.swing.JComboBox<String> CrsInstructor;
    private javax.swing.JTextField CrsName;
    private javax.swing.JButton CrsSaveButton;
    private javax.swing.JTextField LecID;
    private javax.swing.JTextField LecName;
    private javax.swing.JButton LecSaveButton;
    private javax.swing.JPanel LecturerPanel;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JTextField StudID;
    private javax.swing.JList<String> StudList;
    private javax.swing.JTextField StudName;
    private javax.swing.JButton StudSaveButton;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JPanel SubCrsPanel;
    private javax.swing.JPanel SubLecPanel;
    private javax.swing.JPanel SubStudPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
